apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-sample-postgres-pvc
  namespace: dev-sample-postgres
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
