apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-sample-postgres-deployment
  namespace: dev-sample-postgres
spec:
  selector:
    matchLabels:
      app: dev-sample-postgres-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: dev-sample-postgres-deployment
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: dev-sample-postgres-pvc
          env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_DB
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
      volumes:
        - name: dev-sample-postgres-pvc
          persistentVolumeClaim:
            claimName: dev-sample-postgres-pvc
